### ISSUE TITLE
add dtype?

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/mosaicjson-spec#11]
When creating tiles dynamically from the mosaicjson it will be nice to know in advance what kind of data the tiler will read (to determine if rescaling/color correction) is needed.

The data_type should be optional. 

Note: We never addressed the fact the mosaic could have multiple data types but `cogeo-mosaic` enforce it. Maybe we should also mention it in the specs.

**Comment by kylebarron** [comment]
I think it'll be reasonably often to have multiple data types in a Mosaic

**Comment by vincentsarago** [comment]
> I think it'll be reasonably often to have multiple data types in a Mosaic

@kylebarron I will tend to disagree and also this makes dynamic tiling complicated.

**Comment by kylebarron** [comment]
I suppose you're right. If you combine two images with different dtypes, there will be a scaling issue. 

I haven't actually used multiple dtypes yet.

**Comment by kylebarron** [comment]
What's the case for needing to know this in advance?

**Comment by vincentsarago** [comment]
https://github.com/developmentseed/cogeo-mosaic-tiler/blob/master/cogeo_mosaic_tiler/handlers/app.py#L181-L195

this is mostly a frontend issue, where the client will have to add rescaling before being able to request tile when datatype isn't in byte
