### ISSUE TITLE
Should datatype be unique?

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/mosaicjson-spec#12]
discussion started in #11 

I don't think mosaicjson specification should enforce unique datatype among a list of COG but at least this should be referenced somewhere as a `best` practices. 

This is an implementation problem but would be nice to mention it in somewhere here.

**Comment by kylebarron** [comment]
Yeah I agree, it's an implementation issue, which could theoretically be solved (i.e. rescale each numpy array to a common dtype (float32/64?) and then rescale again to the output dtype).

So I don't think the spec should outlaw it.
