### ISSUE TITLE
Support other projection

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/mosaicjson-spec#13]
As of today, mosaicjson has been designed for WebMercator projection, but quadkey could represent tiles in other projections. 

To keep it simple, the projection option should be the name of the TileMatrixSet (TMS) and default to `WebMercatorQuad`.

ref: https://github.com/developmentseed/morecantile

**Comment by kylebarron** [comment]
> To keep it simple, the projection option should be the name of the TileMatrixSet (TMS) and default to `WebMercatorQuad`.

Does that mean you won't support custom grids?

**Comment by vincentsarago** [comment]
@kylebarron well there is not an official list of TileMatrixSet (just a spec) so IMO they are more or less all custom 😂 (in their content). 

we could maybe allow either a `string` or a `dict` to define a grid but I'm affraid this will turn to be a 🕳️

**Comment by kylebarron** [comment]
Yes, but you're able to make a custom grid from a CRS and an extent, so there's no reason why you couldn't have:
```
projection: {
	"tile_matrix_set": "WebMercatorQuad"
}
```
but also
```
projection: {
	"crs": "wkt representation of crs",
	"extent": [a, b, c, d]
}
```
so that you could always encode any arbitrary grid
