### ISSUE TITLE
asset Minetype

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/mosaicjson-spec#14]
ref: https://github.com/developmentseed/cogeo-mosaic/issues/80

From the spec:
>     // Values MUST be arrays of strings (url or sceneid) pointing to a 
    // Cloud Optimized dataset with bounds intersecting with the quadkey bounds.

While this is pretty basic, we are already using mosaicjson with asset being the landsat scene id (awspds stack).

As discussed in cogeo-mosaic issue, it would be nice to have a field in the mosaic that could indicate the tiler what assets it will be.

**Comment by kylebarron** [comment]
Isn't this basically what I was talking about here https://github.com/developmentseed/cogeo-mosaic-tiler/issues/8

**Comment by vincentsarago** [comment]
@kylebarron you proposed `mission = landsat8` and `Minetype` is quite different and my point still stand about `mission`

> I'm 👎 on making change in mosaic-json. What if someone wants to use landsat8 on GCP, or different level L1C L2A. mosaic-json shouldn't be tied to rio-tiler specifics.

But as I also said in the previous ticket: https://github.com/developmentseed/cogeo-mosaic-tiler/issues/8#issuecomment-623800387 ;-)

**Comment by kylebarron** [comment]
This is almost exactly what I proposed in my [follow up comment](https://github.com/developmentseed/cogeo-mosaic-tiler/issues/8#issuecomment-605716321)...

I proposed a keyword that identifies the type of assets in the mosaic. Whether you want to call that keyword "mission" or "mimetype" really makes no difference. 

As an aside, I wouldn't call it MIME type because that specifically refers to how to interpret an arbitrary binary blob, and I think using it here to define the keys of the mosaic would be confusing.

**Comment by vincentsarago** [comment]
To be honest I'm still not sure this is the best way to handle this. I kinda like the other idea of indicating the tiler with a custom url `stac+mosaicid://aaaaaaa` or `landsat+mosaicid://aaaa` so we don't have to touch the spec but only the tiler ;-)

**Comment by vincentsarago** [comment]
☝️ hided my previous comment because my `stac+mosaicid://aaaaaaa` reference makes no sense as we are talking about assets and not mosaic url ;-) 

I agree having `asset type` (e.g COG, STAC, SCENEID ...) might be usefull. 

I'm totally open on the naming.

**Comment by kylebarron** [comment]
Given the link from the other PR, I think I still didn't make myself understood. There are two different questions here:

- resolving the value in `tiles`. 
- knowing what that link points to.

The first is my original complaint, that when the values of `tiles` are _`sceneids`_, the strings are not fully qualified, and there's no way to locate those assets without external information.

The second is what is linked in the 0.0.3 PR, knowing the type of the assets that are pointed to in the `tiles` object.
